FROM node:22-bookworm

RUN apt update && apt upgrade -y

ENV DEBIAN_FRONTEND=noninteractive


WORKDIR /workspace/champions-league-api

COPY ["package.json", "README.md", "jest.config.js","./tests", "./src", "./docs", "LICENSE", "tsconfig.json", "./"]

RUN npm install ci --include prod

CMD ["/bin/bash"]